=== megu-hub/sew-MotoGP/MotoGP-Desktop/xml/circuito.dtd
<!-- Circuito RaÃ­z-->
<!ELEMENT circuito (nombre, longitudTramo, anchuraTramo, fecha, inicio, vueltas, localidadProx, pais, patrocinador, referencias,fotos,videos,puntos,vencedor,clasificados)>

<!-- Circuito sub-elements -->
<!ELEMENT nombre (#PCDATA)>

<!ELEMENT longitudTramo (#PCDATA)>
<!ATTLIST longitudTramo unidades CDATA #REQUIRED>

<!ELEMENT anchuraTramo (#PCDATA)>
<!ATTLIST anchuraTramo unidades CDATA #REQUIRED>

<!ELEMENT fecha (#PCDATA)>
<!ELEMENT inicio (#PCDATA)>
<!ELEMENT vueltas (#PCDATA)>
<!ELEMENT localidadProx (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT patrocinador (#PCDATA)>

<!ELEMENT referencias (referencia+)>
<!ELEMENT referencia (#PCDATA)>
<!ATTLIST referencia rDescripcion CDATA #REQUIRED
    url CDATA #REQUIRED>
 
<!ELEMENT fotos (foto+)>
<!ELEMENT foto (#PCDATA)>
<!ATTLIST foto fDescripcion CDATA #REQUIRED>

<!ELEMENT videos (video+)>
<!ELEMENT video (#PCDATA)>
<!ATTLIST video vDescripcion CDATA #REQUIRED>

<!ELEMENT puntos (punto*)>
<!ELEMENT punto (pLongitud, pLatitud, pAltitud)>
<!ELEMENT pLongitud (#PCDATA)>
<!ELEMENT pLatitud (#PCDATA)>
<!ELEMENT pAltitud (#PCDATA)>

<!ELEMENT vencedor (#PCDATA)>
<!ATTLIST vencedor tiempo CDATA #REQUIRED>

<!ELEMENT clasificados (clasificado+)>
<!ELEMENT clasificado (#PCDATA)>

=== megu-hub/sew-MotoGP/MotoGP-Desktop/xml/circuito.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE circuito SYSTEM "circuito.dtd">
<circuito>
<nombre>Termas del Río Hondo</nombre>
<longitudTramo unidades="m">4800</longitudTramo>
<anchuraTramo unidades="m">16</anchuraTramo>
<fecha>16-03-25</fecha>
<inicio>19:00h</inicio>
<vueltas>25</vueltas>
<localidadProx>Santiago de Estero</localidadProx>
<pais>Argentina</pais>
<patrocinador>YPF</patrocinador>
<referencias>
    <referencia rDescripcion="Wikipedia del Autódromo de Termas de Río Hondo" 
        url="https://es.wikipedia.org/wiki/Autódromo_Internacional_de_Termas_de_Río_Hondo">Wikipedia
    </referencia>

    <referencia rDescripcion="Página oficial del Autódromo de Termas de Río Hondo" 
        url="https://autodromotermas.com">Autódromo de Termas de Río Hondo
    </referencia>

    <referencia rDescripcion="Más información del circuito" 
        url="https://actc.org.ar/tc/circuitos/termas-de-rio-hondo-largo_20.html">ACTC Argentina
    </referencia>
</referencias>
<fotos>
    <foto fDescripcion="Foto del circuito">../multimedia/termas.jpg</foto>
    <foto fDescripcion="Mapa del circuito">../multimedia/circuito.jpg</foto>
</fotos>
<videos>
    <video vDescripcion="Video del circuito con un motorista recorriendolo">../multimedia/circuito.mp4</video>
</videos>
<puntos>
    <punto>
        <pLongitud>-64.91871078280222</pLongitud> 
        <pLatitud>-27.51117626383401</pLatitud>
        <pAltitud>282.2464555077356</pAltitud>
    </punto>
    
    <punto>
        <pLongitud>-64.92147777674616</pLongitud> 
        <pLatitud>-27.51029291472771</pLatitud>
        <pAltitud>281.2311628331676</pAltitud>
    </punto>
    <punto>
        <pLongitud>-64.9216676283641</pLongitud> 
        <pLatitud>-27.50987649219967</pLatitud>
        <pAltitud>280.9854708244442</pAltitud>
    </punto>
    <punto>
        <pLongitud>-64.92154906352468</pLongitud> 
        <pLatitud>-27.50937824630419</pLatitud>
        <pAltitud>281.0320240640369</pAltitud>
    </punto>
    <punto>
        <pLongitud>-64.92105526630372</pLongitud> 
        <pLatitud>-27.5091582774755</pLatitud>
        <pAltitud>281.2310590786101</pAltitud>
    </punto>
    
    <punto>
        <pLongitud>-64.92060924115633</pLongitud> 
        <pLatitud>-27.5091780661173</pLatitud>
        <pAltitud>281.8452860178999</pAltitud>
    </punto>
    <punto>
        <pLongitud>-64.92018646488508</pLongitud> 
        <pLatitud>-27.50929106548936</pLatitud>
        <pAltitud>281.7531809400226</pAltitud>
    </punto>
    <punto>
        <pLongitud>-64.91982925200728</pLongitud> 
        <pLatitud>-27.50945278451242</pLatitud>
        <pAltitud>282.1986931624982</pAltitud>
    </punto>
    <punto>
        <pLongitud>-64.91848017958735</pLongitud> 
        <pLatitud>-27.51012767201232</pLatitud>
        <pAltitud>283.0889516248541</pAltitud>
    </punto>
    <punto>
        <pLongitud>-64.9180686373664</pLongitud> 
        <pLatitud>-27.51019184940634</pLatitud>
        <pAltitud>283.0889830470244</pAltitud>
    </punto>
    <punto>
        <pLongitud>-64.91781031969133</pLongitud> 
        <pLatitud>-27.50995373453803</pLatitud>
        <pAltitud>283.0889714766151</pAltitud>
    </punto>
    <punto>
        <pLongitud>-64.91777041584612</pLongitud> 
        <pLatitud>-27.50954493088422</pLatitud>
        <pAltitud>282.7848211146518</pAltitud>
    </punto>
    <punto>
        <pLongitud>-64.91840668467944</pLongitud> 
        <pLatitud>-27.50848727519009</pLatitud>
        <pAltitud>281.2345825603518</pAltitud>
    </punto>
    <punto>
        <pLongitud>-64.91813611971655</pLongitud> 
        <pLatitud>-27.50781744142549</pLatitud>
        <pAltitud>282.2958906704603</pAltitud>
    </punto>
    <punto>
        <pLongitud>-64.91728702810164</pLongitud> 
        <pLatitud>-27.50673053606156</pLatitud>
        <pAltitud>283.6084602034509</pAltitud>
    </punto>
    <punto>
        <pLongitud>-64.91665543334095</pLongitud> 
        <pLatitud>-27.50623758819906</pLatitud>
        <pAltitud>285.9102819494904</pAltitud>
    </punto>
    
    <punto>
        <pLongitud>-64.91028405040332</pLongitud> 
        <pLatitud>-27.50223537315032</pLatitud>
        <pAltitud>291.3523644107403</pAltitud>
    </punto>
    <punto>
        <pLongitud>-64.9099466134959</pLongitud> 
        <pLatitud>-27.50218326070431</pLatitud>
        <pAltitud>290.9798261214025</pAltitud>
    </punto>

    <punto>
        <pLongitud>-64.90958258017955</pLongitud> 
        <pLatitud>-27.50245372026103</pLatitud>
        <pAltitud>291.8398174343399</pAltitud>
    </punto>
    <punto>
        <pLongitud>-64.90977987212791</pLongitud> 
        <pLatitud>-27.50290786863351</pLatitud>
        <pAltitud>290.8100355828718</pAltitud>
    </punto>
    <punto>
        <pLongitud>-64.91077870588283</pLongitud> 
        <pLatitud>-27.503781946732</pLatitud>
        <pAltitud>288.3672538666129</pAltitud>
    </punto>
    <punto>
        <pLongitud>-64.91115445140271</pLongitud> 
        <pLatitud>-27.50455270745872</pLatitud>
        <pAltitud>287.0191391862004</pAltitud>
    </punto>
    <punto>
        <pLongitud>-64.91127008785857</pLongitud> 
        <pLatitud>-27.50532743718574</pLatitud>
        <pAltitud>286.1765263563452</pAltitud>
    </punto>
    <punto>
        <pLongitud>-64.91106390706435</pLongitud> 
        <pLatitud>-27.50614148656119</pLatitud>
        <pAltitud>285.0766930655725</pAltitud>
    </punto>
    
    <punto>
        <pLongitud>-64.90948961334668</pLongitud> 
        <pLatitud>-27.50852394502786</pLatitud>
        <pAltitud>283.581771725452</pAltitud>
    </punto>
    <punto>
        <pLongitud>-64.90973804704362</pLongitud> 
        <pLatitud>-27.50887140338501</pLatitud>
        <pAltitud>283.7341711848714</pAltitud>
    </punto>
    <punto>
        <pLongitud>-64.91051026395333</pLongitud> 
        <pLatitud>-27.50899249985923</pLatitud>
        <pAltitud>283.2437273667991</pAltitud>
    </punto>
    
    <punto>
        <pLongitud>-64.9111208329803</pLongitud> 
        <pLatitud>-27.50880608897324</pLatitud>
        <pAltitud>283.5598275184207</pAltitud>
    </punto>
    <punto>
        <pLongitud>-64.91273615901531</pLongitud> 
        <pLatitud>-27.50686919947426</pLatitud>
        <pAltitud>284.637406310353</pAltitud>
    </punto>
    <punto>
        <pLongitud>-64.91325828145948</pLongitud> 
        <pLatitud>-27.50683691589784</pLatitud>
        <pAltitud>285.1746833170335</pAltitud>
    </punto>
    <punto>
        <pLongitud>-64.91381563585009</pLongitud> 
        <pLatitud>-27.50715432358833</pLatitud>
        <pAltitud>285.722689301512</pAltitud>
    </punto>

    <punto>
        <pLongitud>-64.91548764738029</pLongitud> 
        <pLatitud>-27.50738793671063</pLatitud>
        <pAltitud>284.7210073807505</pAltitud>
    </punto>
    <punto>
        <pLongitud>-64.9161238562853</pLongitud> 
        <pLatitud>-27.50775206612225</pLatitud>
        <pAltitud>284.6282370361709</pAltitud>
    </punto>
    <punto>
        <pLongitud>-64.91643984516989</pLongitud> 
        <pLatitud>-27.50835283249297</pLatitud>
        <pAltitud>283.9912349466003</pAltitud>
    </punto>
    <punto>
        <pLongitud>-64.9164294454425</pLongitud> 
        <pLatitud>-27.50934451824901</pLatitud>
        <pAltitud>284.6284530897622</pAltitud>
    </punto>
    <punto>
        <pLongitud>-64.91529511831143</pLongitud> 
        <pLatitud>-27.51111831925754</pLatitud>
        <pAltitud>286.3625717184912</pAltitud>
    </punto>

    <punto>
        <pLongitud>-64.91507645572274</pLongitud> 
        <pLatitud>-27.5116752077443</pLatitud>
        <pAltitud>285.4868691365367</pAltitud>
    </punto>
    <punto>
        <pLongitud>-64.91500854354814</pLongitud> 
        <pLatitud>-27.51242125160185</pLatitud>
        <pAltitud>284.1447720393834</pAltitud>
    </punto>
    <punto>
        <pLongitud>-64.91508949858374</pLongitud> 
        <pLatitud>-27.51275938102797</pLatitud>
        <pAltitud>283.4170877337825</pAltitud>
    </punto>
    <punto>
        <pLongitud>-64.91536359229025</pLongitud> 
        <pLatitud>-27.51297768453737</pLatitud>
        <pAltitud>283.0890428498708</pAltitud>
    </punto>

    <punto>
        <pLongitud>-64.9157191024575</pLongitud> 
        <pLatitud>-27.51283859816818</pLatitud>
        <pAltitud>282.8408132292891</pAltitud>
    </punto>
    <punto>
        <pLongitud>-64.91591697710078</pLongitud> 
        <pLatitud>-27.51249081544245</pLatitud>
        <pAltitud>283.0890558207819</pAltitud>
    </punto>
    <punto>
        <pLongitud>-64.91611039523447</pLongitud> 
        <pLatitud>-27.51203930611695</pLatitud>
        <pAltitud>283.5510051018794</pAltitud>
    </punto>
    
    <punto>
        <pLongitud>-64.91871078280222</pLongitud> 
        <pLatitud>-27.51117626383401</pLatitud>
        <pAltitud>282.2464555077356</pAltitud>
    </punto>
</puntos>

<vencedor tiempo="41:11.100">Mark Marquéz</vencedor>
<clasificados>
    <clasificado>M. Marquez</clasificado>
    <clasificado>A. Marquez</clasificado>
    <clasificado>M. Bezzecchi</clasificado>
</clasificados>
</circuito>
